---
- name: Write WordPress plugin options to file
  copy:
    content: "{{ plugin_option.value | to_json }}"
    dest: "{{ plugin_tmp_file.path }}"
  changed_when: False

- name: Configure plugin '{{ plugin.name }}' on instance '{{ wp_instance.name | mandatory }}'
  become_user: www-data
  shell: "wp option update {{ plugin_option.key }} --path={{ wordpress_instance_path }} --format=json < {{ plugin_tmp_file.path }}"
  register: output
  changed_when: "'Updated' in output.stdout"
