---
- name: "Read {{ item.key }}"
  shell: "sudo -u www-data wp option get {{ item.key }} --path=/var/www/wordpress --format=json"
  changed_when: False
  register: result

- name: Write merged settings to file
  copy:
    content: "{{  result.stdout | from_json | combine( item.value ) | to_json }}"
    dest: "{{ tmp_file.path }}"
  changed_when: False

- name: "Configure {{ plugin.name }}"
  shell: "sudo -u www-data wp option update {{ item.key }} --path=/var/www/wordpress --format=json < {{ tmp_file.path }}"
  register: output
  changed_when: "'Updated' in output.stdout"
