---
- name: Create WordPress admins
  become_user: www-data
  command: "wp user create {{ item.key }} {{ item.value.email }} --display_name='{{ item.value.name }}' --user_pass={{ item.value.password }} --role=administrator --path=/var/www/wordpress"
  when: item.value.email is defined and item.value.password is defined
  register: result
  changed_when: "'Created user' in result.stdout"
  failed_when: "result.rc != 0 and not 'username is already registered' in result.stderr"
  loop: "{{ wordpress_admins | dict2items }}"

- name: Create WordPress admins
  become_user: www-data
  command: "wp user create {{ item.key }} {{ item.value.email }} --display_name='{{ item.value.name }}' --role=administrator --path=/var/www/wordpress"
  when: item.value.email is defined and not item.value.password is defined
  register: result
  changed_when: "'Created user' in result.stdout"
  failed_when: "result.rc != 0 and not 'username is already registered' in result.stderr"
  loop: "{{ wordpress_admins | dict2items }}"

- name: Update WordPress admins
  become_user: www-data
  command: "wp user update {{ item.key }} --user_email='{{ item.value.email }}' --display_name='{{ item.value.name }}' --role=administrator --path=/var/www/wordpress"
  when: "item.value.email is defined and not item.value.password is defined"
  changed_when: false
  loop: "{{ wordpress_admins | dict2items }}"

- name: Update WordPress admins
  become_user: www-data
  command: "wp user update {{ item.key }} --user_email='{{ item.value.email }}' --display_name='{{ item.value.name }}' --user_pass={{ item.value.password }} --role=administrator --path=/var/www/wordpress"
  when: "item.value.email is defined and item.value.password is defined"
  changed_when: false
  loop: "{{ wordpress_admins | dict2items }}"

