---
- name: "Read plugin options for '{{ plugin.name }}'"
  become_user: www-data
  command: "wp option get {{ plugin_option.key }} --path=/var/www/wordpress --format=json"
  changed_when: False
  register: existing_plugin_settings

- name: Write merged settings to file
  copy:
    content: "{{ existing_plugin_settings.stdout | from_json | combine( plugin_option.value ) | to_json }}"
    dest: "{{ plugin_tmp_file.path }}"
  changed_when: False

- name: "Configure plugin '{{ plugin.name }}'"
  become_user: www-data
  shell: "wp option update {{ plugin_option.key }} --path=/var/www/wordpress --format=json < {{ plugin_tmp_file.path }}"
  register: output
  changed_when: "'Updated' in output.stdout"
