---
- name: Create temporary file to store existing plugin options
  tempfile:
    state: file
  register: plugin_tmp_file
  changed_when: False

- name: Set owner for temporary file
  file:
    path: "{{ plugin_tmp_file.path }}"
    owner: www-data
    group: www-data
    mode: 0600
  changed_when: False

- name: "Configure plugin and merge options"
  include_tasks: configure_option_merge.yml
  when: "plugin.options is defined and plugin.merge | default(wordpress_plugin_merge_default)"
  loop: "{{ plugin.options | dict2items}}"
  loop_control:
    loop_var: plugin_option

- name: "Configure plugin and overwrite options"
  include_tasks: configure_option_overwrite.yml
  when: "plugin.options is defined and not plugin.merge | default(wordpress_plugin_merge_default)"
  loop: "{{ plugin.options | dict2items }}"
  loop_control:
    loop_var: plugin_option

- name: Delete temporary file
  file:
    path: "{{ plugin_tmp_file.path }}"
    state: absent
  changed_when: False
