---
- name: Create tmp file
  tempfile:
    state: file
  register: tmp_file
  changed_when: False

- name: Set owner for tmp file
  file:
    path: "{{ tmp_file.path }}"
    owner: www-data
    group: www-data
    mode: 0600
  changed_when: False

- name: "Configure plugin and merge options"
  include_tasks: configure_option_merge.yml
  when: "{{ plugin.options }} is defined and {{ plugin.merge | default(wordpress_plugin_merge_default) }}"
  with_dict: "{{ plugin.options }}"

- name: "Configure plugin and overwrite options"
  include_tasks: configure_option_overwrite.yml
  when: "{{ plugin.options }} is defined and not {{ plugin.merge | default(wordpress_plugin_merge_default) }}"
  with_dict: "{{ plugin.options }}"

- name: Delete tmp file
  file:
    path: "{{ tmp_file.path }}"
    state: absent
  changed_when: False
