
- name: Write settings to file
  copy:
    content: "{{ item.value | to_json }}"
    dest: "{{ tmp_file.path }}"
  changed_when: False

- name: "Configure {{ plugin.name }}"
  become: yes
  become_user: www-data
  shell: "wp option update {{ item.key }} --path=/var/www/wordpress --format=json < {{ tmp_file.path }}"
  register: output
  changed_when: "'Updated' in output.stdout"

