---
- name: "Read {{ item.key }}"
  become: yes
  become_user: www-data
  shell: "wp option get {{ item.key }} --path=/var/www/wordpress --format=json"
  changed_when: False
  register: result

- name: Read output form json to yaml
  set_fact:
    option_plugin: "{{ result.stdout | from_json }}"

- name: Merge settings
  set_fact:
    option_merged: "{{ option_plugin | combine( item.value ) }}"

- name: Write merged settings to file
  copy:
    content: "{{ option_merged | to_json }}"
    dest: "{{ tmp_file.path }}"
  changed_when: False

- name: "Configure {{ plugin.name }}"
  become: yes
  become_user: www-data
  shell: "wp option update {{ item.key }} --path=/var/www/wordpress --format=json < {{ tmp_file.path }}"
  register: output
  changed_when: "'Updated' in output.stdout"

