---
- name: Install required packages
  apt:
    name:
      - php-mysql
      - python-mysqldb
      - python3-mysqldb
      - php-ldap
      - php-imagick
      - php-gd
      - php-mbstring
      - php-mcrypt
      - php-curl
