---
- block:
  - import_tasks: install_packages.yml
  - import_tasks: install_wp_cli.yml
  - name: Download latest WordPress version to localhost
    get_url:
      url: https://wordpress.org/latest.tar.gz
      dest: "{{ global_cache_dir | mandatory }}/wordpress_latest.tar.gz"
    become: False
    delegate_to: localhost
    run_once: True
  when: wordpress_instances | length > 0

- include_tasks: setup_wp_instance.yml
  loop: "{{ wordpress_instances }}"
  loop_control:
    loop_var: wp_instance
    label: "{{ wp_instance.name }}"

# mandatory: name, home, siteurl, mysql_password, default_password, blogname, blogdescription