---
- name: Install required packages
  apt:
    name: "{{ item }}"
  with_items:
    - php-mysql
    - python-mysqldb
    - php-ldap
    - php-imagick
    - php-gd
    - php-mbstring
    - php-mcrypt
    - php-curl
  when: ansible_pkg_mgr == "apt"

- stat:
    path: /var/www/wordpress
  register: wordpress_dir_exists

- file:
    path: /var/www/
    state: directory
    mode: 0755
  when: not wordpress_dir_exists.stat.exists

- include: install.yml
  when: not wordpress_dir_exists.stat.exists