---
- block:
  - import_tasks: install_packages.yml
  - import_tasks: install_wp_cli.yml
  - name: Remove anonymous DB user account
    mysql_user:
      name: ''
      host: localhost
      state: absent
  when: wordpress_instances | length > 0

- include_tasks: setup_wp_instance.yml
  loop: "{{ wordpress_instances }}"
  loop_control:
    loop_var: wp_instance
    label: "{{ wp_instance.name }}"

# mandatory: name, home, siteurl, mysql_password, default_password, blogname, blogdescription