---
- import_tasks: install_packages.yml
- import_tasks: install_wp_client.yml

- stat:
    path: /var/www/wordpress
  register: wordpress_dir_exists

- file:
    path: /var/www/
    state: directory
    mode: 0755
  when: not wordpress_dir_exists.stat.exists

- import_tasks: install.yml
  when: not wordpress_dir_exists.stat.exists

- import_tasks: plugins.yml

- import_tasks: configure.yml

- name: Update wordpress
  become_user: www-data
  shell: wp core update --path=/var/www/wordpress
  register: result
  changed_when: "not 'Success: WordPress is up to date' in result.stdout"

