---
- name: Remove anonymous DB user account
  mysql_user:
    name: ''
    host: localhost
    state: absent

- name: Create DB user
  mysql_user:
    name: "{{ wordpress_mysql_user }}"
    password: "{{ wordpress_mysql_password }}"
    priv: '{{ wordpress_mysql_database_name }}.*:ALL,GRANT'

- name: Create a new database with name '{{ wordpress_mysql_database_name }}'
  mysql_db:
    name: "{{ wordpress_mysql_database_name }}"

- name: Check if DB contains any tables
  shell: >
    mysql --user={{ wordpress_mysql_user }}
    --password={{ wordpress_mysql_password }}
    --database={{ wordpress_mysql_database_name }} -e "show tables;"
  register: wp_tables

- name: Create SQL tempfile
  tempfile:
    state: file
    suffix: .wordpress.sql
  register: wp_sql_file
  when: wordpress_import_db_file or wp_tables.stdout == ""

- name: Create new WordPress SQL file
  template:
    src: templates/wordpress.sql.j2
    dest: "{{ wp_sql_file.path }}"
  when:
    - not wordpress_import_db_file
    - wp_tables.stdout == ""

- name: Copy WordPress SQL file from localhost
  copy:
    src: "{{ inventory_hostname }}/wordpress.sql"
    dest: "{{ wp_sql_file.path }}"
  when: wordpress_import_db_file

- name: Import WordPress SQL file
  mysql_db:
    state: import
    name: "{{ wordpress_mysql_database_name }}"
    target: "{{ wp_sql_file.path }}"
  when: wordpress_import_db_file or wp_tables.stdout == ""

- name: Remove SQL tempfile
  file:
    path: "{{ wp_sql_file.path }}"
    state: absent
  when: wp_sql_file.path is defined
