---
- name: Install plugins
  become_user: www-data
  command: "wp plugin install {{ item.name }} --path=/var/www/wordpress --activate"
  register: output
  changed_when: "'Installing' in output.stdout"
  loop: "{{ wordpress_plugins }}"

- name: Configure plugin
  include_tasks: configure_plugin.yml
  loop: "{{ wordpress_plugins }}"
  loop_control:
    loop_var: plugin

- name: Update plugins
  become_user: www-data
  command: wp plugin update --all --path=/var/www/wordpress
